-- BookPulse production database schema for Supabase/Postgres.
-- Run this once in Supabase SQL Editor before deploying with cloud persistence.

create table if not exists readers (
  id text primary key,
  display_name text not null,
  country text not null,
  state text not null,
  yearly_goal integer not null default 100 check (yearly_goal between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists reader_books (
  reader_id text not null references readers(id) on delete cascade,
  book_id text not null,
  title text not null,
  author text not null,
  category text not null,
  read_at timestamptz not null default now(),
  minutes integer not null default 0,
  primary key (reader_id, book_id)
);

create table if not exists community_visits (
  id bigint generated by default as identity primary key,
  reader_id text references readers(id) on delete set null,
  book_id text,
  is_new_session boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_community_visits_book on community_visits(book_id);
create index if not exists idx_community_visits_created on community_visits(created_at);

create table if not exists book_likes (
  reader_id text not null references readers(id) on delete cascade,
  book_id text not null,
  book_title text,
  created_at timestamptz not null default now(),
  primary key (reader_id, book_id)
);

create table if not exists comments (
  id text primary key,
  book_id text not null,
  book_title text,
  reader_id text not null references readers(id) on delete cascade,
  author text not null,
  country text,
  state text,
  avatar_color text not null,
  content text not null,
  rating integer not null default 5 check (rating between 1 and 5),
  tag text not null default 'Key Takeaway',
  likes_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_comments_book on comments(book_id);
create index if not exists idx_comments_created on comments(created_at desc);

create table if not exists comment_likes (
  reader_id text not null references readers(id) on delete cascade,
  comment_id text not null references comments(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (reader_id, comment_id)
);

-- This app accesses Supabase through the server using the service-role key.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser.

-- Lock direct browser access down; the Express API is the only application path.
alter table readers enable row level security;
alter table reader_books enable row level security;
alter table community_visits enable row level security;
alter table book_likes enable row level security;
alter table comments enable row level security;
alter table comment_likes enable row level security;
